### ISSUE TITLE
Please note that the solution to concat has a teensy mistake

### ISSUE THREAD

**Issue by bhargavrpatel** [brunops/nodeschool-solutions#1]
Hello, 

You should not add the newline character in the solution you provided for concat here (https://github.com/brunops/nodeschool-solutions/blob/master/stream-adventure/concat.js).
Regards,
B

**Comment by brunops** [comment]
I agree. It was an older version of `stream-adventure` and the problem failed without the new line, just updated the module and now it works, thanks :)
